### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by keichi** [keichi/vienna#13]
http://gohugo.io/extras/pagination/

**Comment by mapitman** [comment]
I implemented pagination and submitted a pull request [here](https://github.com/keichi/vienna/pull/14)
It is mixed in with the code to customize the top image per post. Since the original pull request never got merged, my new commit just got added to it.

**Comment by keichi** [comment]
Just merged your PR. I appreciate  for your work here!

**Comment by ethanmad** [comment]
I feel that there should be more separation between the bottom post and the pagination buttons; right now it looks like the buttons are part of the post. Maybe a horizontal line is needed or just increased spacing.

**Comment by mapitman** [comment]
@ethanmad, yeah, i agree it needs something. I played around with the formatting but didn't come up with anything I liked. If you make some changes, you should add it to your site and let us see! I'll try something as well.
