### ISSUE TITLE
Disqus comments

### ISSUE THREAD

**Issue by mapitman** [keichi/vienna#17]
I see you added Disqus support [here](https://github.com/keichi/vienna/commit/e0219f5bb6204f8ee75913d4858abb821c101aa2) but i can't seem to get it to work.

I added a DisqusShortname = "xxx" to my config.toml file, but none of that script gets written out to the page. Any tips for getting it to work?

**Comment by mapitman** [comment]
OK, I figured out what i was doing wrong. I added DisqusShortname to the [params] section and it needs to be at the top level in order to work. Should we move it to [params] though, like google analytics and all the social account links?

**Comment by keichi** [comment]
Thanks for pointing this out. I think all theme specific settings should go under [params]. Fixed with this commit: 46610182d64d902b6724d34dbecbc686732db6dc.
