### ISSUE TITLE
.Prev/.Next ordering in Hugo

### ISSUE THREAD

**Issue by NHOrus** [keichi/vienna#2]
By design, .Prev point to post with earlier date. .Next points to later date. If not set in the post body manually.
So, latest post will ends up as oldest in your theme, when using pagination and not fixing the problem manually.

**Comment by NHOrus** [comment]
From a discussion in Slack:

> Also note the .PrevInSection, which has the same odd behaviour, but is in most cases what you want.

**Comment by keichi** [comment]
Thanks for pointing this out. It's fixed now.
