### ISSUE TITLE
Horizontal scrolling is present when displayed on mobile devices

### ISSUE THREAD

**Issue by ryanewtaylor** [keichi/vienna#31]

**Comment by ethanmad** [comment]
@ryanewtaylor Thanks for the report. Can you share an example of a site where you see this behavior? It looks fine to me on https://www.ethanmad.com.

**Comment by ryanewtaylor** [comment]
It appears that I had an old version as I had originally forked from keichi/vienna. I have updated my fork with the latest from ethanmad/vienna which has a fix for this issue. My site (https://www.iamrewt.com) now has the fix. Is ethanmad/vienna the canonical repository?

**Comment by ethanmad** [comment]
@ryanewtaylor 

This must have been the fix: https://github.com/ethanmad/vienna/commit/09f30774ae6551996a2f48c397277c87dcd4c9d3.

I think @keichi has been busy lately and my fork includes some merged patches & PRs. I won't claim that my repository is the "canonical" one, but it includes a bit more.

**Comment by ryanewtaylor** [comment]
@ethanmad that is indeed the fix. Thanks!
